// jablko_web_interface.js: NodeJS server that runs the web interface for Jablko
// Cale Overstreet, Corinne Gerhold
// April 18, 2020
// Primary server for serving smart home web interface.

const jablko_root = __dirname; // Root of the Jablko Repo
const jablko_web_root = __dirname + "/public_html"; // Root of web assets

const express = require("express"); // Main express include
const axios = require("axios");

const server = express(); // Creating server object

server.use(express.static(`${jablko_web_root}`));

// Load Jablko Modules
const fs = require("fs");
var jablko_modules_dict = new Object();

const module_names = fs.readdirSync(`${jablko_root}/jablko_modules`);
for (var i = 0; i < module_names.length; i++) {
	jablko_modules_dict[module_names] = require(`${jablko_root}/jablko_modules/${module_names[i]}/${module_names[i]}.js`);
}

// Generate dashboard.html from dashboard_template.html
// Replace $JABLKO_MODULES with string containing html generated by each module
console.log("Generating dashboard.html from template...");

var jablko_modules_string = "";
Object.keys(jablko_modules_dict).forEach(function(item) {
	jablko_modules_string += jablko_modules_dict[item].generate_card();
});

var dashboard_template = fs.readFileSync(`${jablko_web_root}/dashboard/dashboard_template.html`).toString();

dashboard_template = dashboard_template.replace("$JABLKO_MODULES", jablko_modules_string);

fs.writeFileSync(`${jablko_web_root}/dashboard/dashboard.html`, dashboard_template);

console.log(`Generated dashboard.html with modules: ${module_names}`);


server.get("/", function(req, res) {
	res.sendFile(`${jablko_web_root}/dashboard/dashboard.html`);
});

server.listen(10230, function() {
	console.log("Jablko Web Interface started on port 10230");
});

process.on("message", function(message) {
	console.log(message);
});
