#!/bin/bash

sudo ./setup_iptables.sh
echo Running as user \"$(whoami)\"
while true
do
	/home/jablko/.deno/bin/deno run --allow-net --allow-run --allow-read --allow-write --unstable jablko_interface.ts
	if (($? != 240))
	then
		exit $?
	fi
done
